
language: en #only en, ru

ItemCanBeLock:
  - FILLED_MAP
  - WRITTEN_BOOK
  - NETHERITE_UPGRADE_SMITHING_TEMPLATE
  - COAST_ARMOR_TRIM_SMITHING_TEMPLATE
  - HOST_ARMOR_TRIM_SMITHING_TEMPLATE
  - VEX_ARMOR_TRIM_SMITHING_TEMPLATE
  - WILD_ARMOR_TRIM_SMITHING_TEMPLATE
  - DUNE_ARMOR_TRIM_SMITHING_TEMPLATE
  - WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE
  - EYE_ARMOR_TRIM_SMITHING_TEMPLATE
  - TIDE_ARMOR_TRIM_SMITHING_TEMPLATE
  - RIB_ARMOR_TRIM_SMITHING_TEMPLATE
  - SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE
  - SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE
  - RAISER_ARMOR_TRIM_SMITHING_TEMPLATE
  - SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE
  - SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE
  - WARD_ARMOR_TRIM_SMITHING_TEMPLATE
  - SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE
  - BOLT_ARMOR_TRIM_SMITHING_TEMPLATE
  - FLOW_ARMOR_TRIM_SMITHING_TEMPLATE

ItemTagCanBeLock:
  #- trim_templates delete in 1.21.4 :(